### ISSUE TITLE
Exercise implementation tracker 

### ISSUE THREAD

**Issue by BNAndras** [exercism/arturo#22]
Tracking for exercises both claimed and merged.

- [x] [allergies] - Andras #64
- [ ] [custom-set] - Andras
- [ ] [pythagorean-triplet] - Andras
- [ ] [resistor-color-trio] - Andras
- [ ] [resistor-color-expert] - Andras
- [x] [robot-simulator] - Andras #78
- [x] [strain] - Andras #72
- [ ] [zebra-puzzle] - Erik
- [x] [acronym] #126 
- [x] [anagram] #70
- [x] [armstrong-numbers] #35
- [x] [atbash-cipher] #87
- [x] [binary-search]  #61
- [x] [bob] #24
- [x] [bottle-song] #134 
- [x] [clock] #131 
- [x] [collatz-conjecture] #23 
- [x] [darts] #10
- [x] [difference-of-squares] #50
- [x] [dnd-character] #9
- [x] [eliuds-eggs] #51
- [x] [etl] #59 
- [x] [flatten-array] #76 
- [x] [food-chain] #145 
- [x] [gigasecond] #28
- [x] [grains] #71
- [x] [hamming] #36
- [x] [hello-world] #4 
- [x] [high-scores] #25
- [x] [house] #135 
- [x] [isbn-verifier] #139
- [x] [isogram] #29
- [x] [kindergarten-garden] #130
- [x] [largest-series-product] #54 
- [x] [leap] #8
- [x] [luhn] #127 
- [x] [matching-brackets] #75
- [x] [matrix]  #140 
- [x] [nucleotide-count] #31
- [x] [pangram] #7
- [x] [pascals-triangle] #77 
- [x] [perfect-numbers] #60
- [x] [phone-number] #86
- [x] [prime-factors] #52
- [x] [protein-translation] #69
- [x] [nth-prime]  #143
- [x] [proverb] #129
- [x] [queen-attack] #124
- [x] [raindrops] #27
- [x] [resistor-color] #30
- [x] [resistor-color-duo] #6
- [x] [reverse-string] #53
- [x] [roman-numerals] #56
- [x] [rotational-cipher] #73 
- [x] [rna-transcription] #21
- [x] [run-length-encoding] #67
- [x] [scrabble-score] #63 
- [x] [secret-handshake] #65 
- [x] [series] #32
- [x] [sieve] #144
- [x] [square-root] #68 
- [x] [space-age] #62
- [x] [sum-of-multiples] #37
- [x] [transpose] #141
- [x] [triangle] #74 
- [x] [twelve-days]  #138 
- [x] [two-fer] #5
- [x] [word-count] #132 
- [x] [yacht] #58 

[acronym]: https://github.com/exercism/problem-specifications/tree/main/exercises/acronym
[allergies]: https://github.com/exercism/problem-specifications/tree/main/exercises/allergies
[alphametics]: https://github.com/exercism/problem-specifications/tree/main/exercises/alphametics
[anagram]: https://github.com/exercism/problem-specifications/tree/main/exercises/anagram
[armstrong-numbers]: https://github.com/exercism/problem-specifications/tree/main/exercises/armstrong-numbers
[atbash-cipher]: https://github.com/exercism/problem-specifications/tree/main/exercises/atbash-cipher
[bank-account]: https://github.com/exercism/problem-specifications/tree/main/exercises/bank-account
[binary-search-tree]: https://github.com/exercism/problem-specifications/tree/main/exercises/binary-search-tree
[binary-search]: https://github.com/exercism/problem-specifications/tree/main/exercises/binary-search
[bob]: https://github.com/exercism/problem-specifications/tree/main/exercises/bob
[bottle-song]: https://github.com/exercism/problem-specifications/tree/main/exercises/bottle-song
[circular-buffer]: https://github.com/exercism/problem-specifications/tree/main/exercises/circular-buffer
[clock]: https://github.com/exercism/problem-specifications/tree/main/exercises/clock
[collatz-conjecture]: https://github.com/exercism/problem-specifications/tree/main/exercises/collatz-conjecture
[custom-set]: https://github.com/exercism/problem-specifications/tree/main/exercises/custom-set
[darts]: https://github.com/exercism/problem-specifications/tree/main/exercises/darts
[diamond]: https://github.com/exercism/problem-specifications/tree/main/exercises/diamond
[difference-of-squares]: https://github.com/exercism/problem-specifications/tree/main/exercises/difference-of-squares
[dnd-character]: https://github.com/exercism/problem-specifications/tree/main/exercises/dnd-character
[dominoes]: https://github.com/exercism/problem-specifications/tree/main/exercises/dominoes
[eliuds-eggs]: https://github.com/exercism/problem-specifications/tree/main/exercises/eliuds-eggs
[etl]: https://github.com/exercism/problem-specifications/tree/main/exercises/etl
[flatten-array]: https://github.com/exercism/problem-specifications/tree/main/exercises/flatten-array
[food-chain]: https://github.com/exercism/problem-specifications/tree/main/exercises/food-chain
[forth]: https://github.com/exercism/problem-specifications/tree/main/exercises/forth
[gigasecond]: https://github.com/exercism/problem-specifications/tree/main/exercises/gigasecond
[grains]: https://github.com/exercism/problem-specifications/tree/main/exercises/grains
[hamming]: https://github.com/exercism/problem-specifications/tree/main/exercises/hamming
[hello-world]: https://github.com/exercism/problem-specifications/tree/main/exercises/hello-world
[high-scores]: https://github.com/exercism/problem-specifications/tree/main/exercises/high-scores
[house]: https://github.com/exercism/problem-specifications/tree/main/exercises/house
[isbn-verifier]: https://github.com/exercism/problem-specifications/tree/main/exercises/isbn-verifier
[isogram]: https://github.com/exercism/problem-specifications/tree/main/exercises/isogram
[kindergarten-garden]: https://github.com/exercism/problem-specifications/tree/main/exercises/kindergarten-garden
[largest-series-product]: https://github.com/exercism/problem-specifications/tree/main/exercises/largest-series-product
[leap]: https://github.com/exercism/problem-specifications/tree/main/exercises/leap
[lens-person]: https://github.com/exercism/problem-specifications/tree/main/exercises/lens-person
[luhn]: https://github.com/exercism/problem-specifications/tree/main/exercises/luhn
[matching-brackets]: https://github.com/exercism/problem-specifications/tree/main/exercises/matching-brackets
[matrix]: https://github.com/exercism/problem-specifications/tree/main/exercises/matrix
[meetup]: https://github.com/exercism/problem-specifications/tree/main/exercises/meetup
[nth-prime]: https://github.com/exercism/problem-specifications/tree/main/exercises/nth-prime
[nucleotide-count]: https://github.com/exercism/problem-specifications/tree/main/exercises/nucleotide-count
[pangram]: https://github.com/exercism/problem-specifications/tree/main/exercises/pangram
[pascals-triangle]: https://github.com/exercism/problem-specifications/tree/main/exercises/pascals-triangle
[perfect-numbers]: https://github.com/exercism/problem-specifications/tree/main/exercises/perfect-numbers
[phone-number]: https://github.com/exercism/problem-specifications/tree/main/exercises/phone-number
[pig-latin]: https://github.com/exercism/problem-specifications/tree/main/exercises/pig-latin
[pov]: https://github.com/exercism/problem-specifications/tree/main/exercises/pov
[prime-factors]: https://github.com/exercism/problem-specifications/tree/main/exercises/prime-factors
[protein-translation]: https://github.com/exercism/problem-specifications/tree/main/exercises/protein-translation
[proverb]: https://github.com/exercism/problem-specifications/tree/main/exercises/proverb
[pythagorean-triplet]: https://github.com/exercism/problem-specifications/tree/main/exercises/pythagorean-triplet
[queen-attack]: https://github.com/exercism/problem-specifications/tree/main/exercises/queen-attack
[raindrops]: https://github.com/exercism/problem-specifications/tree/main/exercises/raindrops
[react]: https://github.com/exercism/problem-specifications/tree/main/exercises/react
[resistor-color]: https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color
[resistor-color-duo]: https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-duo
[resistor-color-trio]: https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-trio
[resistor-color-expert]: https://github.com/exercism/python/blob/main/exercises/practice/resistor-color-expert/resistor_color_expert_test.py
[reverse-string]: https://github.com/exercism/problem-specifications/tree/main/exercises/reverse-string
[rna-transcription]: https://github.com/exercism/problem-specifications/tree/main/exercises/rna-transcription
[robot-name]: https://github.com/exercism/problem-specifications/tree/main/exercises/robot-name
[robot-simulator]: https://github.com/exercism/problem-specifications/tree/main/exercises/robot-simulator
[roman-numerals]: https://github.com/exercism/problem-specifications/tree/main/exercises/roman-numerals
[rotational-cipher]: https://github.com/exercism/problem-specifications/tree/main/exercises/rotational-cipher
[run-length-encoding]: https://github.com/exercism/problem-specifications/tree/main/exercises/run-length-encoding
[scrabble-score]: https://github.com/exercism/problem-specifications/tree/main/exercises/scrabble-score
[secret-handshake]: https://github.com/exercism/problem-specifications/tree/main/exercises/secret-handshake
[series]: https://github.com/exercism/problem-specifications/tree/main/exercises/series
[sieve]: https://github.com/exercism/problem-specifications/tree/main/exercises/sieve
[space-age]: https://github.com/exercism/problem-specifications/tree/main/exercises/space-age
[spiral-matrix]: https://github.com/exercism/problem-specifications/tree/main/exercises/spiral-matrix
[square-root]: https://github.com/exercism/problem-specifications/tree/main/exercises/square-root
[strain]: https://github.com/exercism/problem-specifications/tree/main/exercises/strain
[sum-of-multiples]: https://github.com/exercism/problem-specifications/tree/main/exercises/sum-of-multiples
[transpose]: https://github.com/exercism/problem-specifications/tree/main/exercises/transpose
[triangle]: https://github.com/exercism/problem-specifications/tree/main/exercises/triangle
[twelve-days]: https://github.com/exercism/problem-specifications/tree/main/exercises/twelve-days
[two-bucket]: https://github.com/exercism/problem-specifications/tree/main/exercises/two-bucket
[two-fer]: https://github.com/exercism/problem-specifications/tree/main/exercises/two-fer
[yacht]: https://github.com/exercism/problem-specifications/tree/main/exercises/yacht
[yacht]: https://github.com/exercism/problem-specifications/tree/main/exercises/yacht
[zebra-puzzle]: https://github.com/exercism/problem-specifications/tree/main/exercises/zebra-puzzle
[zebra-puzzle]: https://github.com/exercism/problem-specifications/tree/main/exercises/zebra-puzzle
[zipper]: https://github.com/exercism/problem-specifications/tree/main/exercises/zipper

**Comment by ErikSchierboom** [comment]
I'll do collatz conjecture.

**Comment by ErikSchierboom** [comment]
And `bob`

**Comment by ErikSchierboom** [comment]
And `high-scores`

**Comment by ErikSchierboom** [comment]
I'll do `raindrops`

**Comment by ErikSchierboom** [comment]
I'll do `gigasecond`

**Comment by ErikSchierboom** [comment]
I'll do `nucleotide-count` and `isogram` too.

**Comment by ErikSchierboom** [comment]
And `resistor-color`

**Comment by ErikSchierboom** [comment]
And `series`

**Comment by ErikSchierboom** [comment]
And `difference-of-squares`

**Comment by ErikSchierboom** [comment]
And `eliuds-eggs`

**Comment by ErikSchierboom** [comment]
> this is the sample curriculum from the docs so we shouldn’t deviate too much.

It's totally fine to deviate from this BTW :)

**Comment by ErikSchierboom** [comment]
I'll do `yacht`

**Comment by BNAndras** [comment]
Yup, I was just feeling a bit guilty since I didn't include any hard exercises for Pyret at launch. They were mainly easy with a few mediums. :)

**Comment by ErikSchierboom** [comment]
I'll try `zebra-puzzle` to have a more difficulty exercise.

**Comment by BNAndras** [comment]
I'll work on binary-search, protein-translation, scrabble-score, luhn, pig-latin, space-age, secret-handshake, and robot-simulator. That'll cover us for a lot of the #48in24 exercises so far this year.

**Comment by ErikSchierboom** [comment]
I'll do `square-root` and `run-length-encoding`.

**Comment by BNAndras** [comment]
I'll take `queen-attack` and `phone-number` after `luhn` and `pig-latin`. For `robot-simulator`. I have a working Red solution I can adapt for this track later this week.

**Comment by ErikSchierboom** [comment]
I'll take `rotational-cipher`

**Comment by ErikSchierboom** [comment]
I'll do `matching-brackets` and `flatten-array`.

**Comment by ErikSchierboom** [comment]
@BNAndras We can now use https://exercism.org/challenges/48in24/implementation_status/arturo t check the 48in24 progress for Arturo. See https://forum.exercism.org/t/track-specific-implementation-status-page/11588

**Comment by ErikSchierboom** [comment]
I'll take `pascals-triangle` too

**Comment by ErikSchierboom** [comment]
I'll do food-chain

**Comment by BNAndras** [comment]
I’ll do spiral matrix.

**Comment by BNAndras** [comment]
and yacht

**Comment by ErikSchierboom** [comment]
I'll do `list-ops`

**Comment by BNAndras** [comment]
I’ll pick this back up beginning this weekend.

**Comment by BNAndras** [comment]
I'll add acronym and atbash-cipher as well.

**Comment by ErikSchierboom** [comment]
Perfect. I haven't done anything on the Arturo track as the Docker issues haven't yet been solved, and without those solved, there won't be a test runner.

**Comment by drkameleon** [comment]
@ErikSchierboom I'm on to it! I'll let you know about the progress today! 😉

**Comment by drkameleon** [comment]
And... 🥁 🥁 🥁 :

https://discord.com/channels/765519132186640445/1244603305846640660/1272854929966628915

(I'm posting the link here in order to avoid posting the same things in two different places 😉 )

**Comment by ErikSchierboom** [comment]
Thanks a ton!

**Comment by drkameleon** [comment]
> Thanks a ton!

Thank *you*! 😉

**Comment by BNAndras** [comment]
I’ll grab `resistor-color-trio` and bring over `resistor-color-expert` from Python. It’ll be another relevant place to highlight quantities and use `:color` to represent the input colors more directly. I could add the input color thing to `resistor-color-duo` but `resistor-color` would remain strings for now. At the moment, colors are printed in hexadecimal notation not the plain English look so the test output for checking the colors variable is hard to read.

**Comment by BNAndras** [comment]
Is it okay if I grab Food Chain from you, Erik? I'll also grab Pythagorean Triplet, returning Pig Latin and Spiral Matrix.

**Comment by ErikSchierboom** [comment]
Sure!
